name: SkypixelHyblock
version: 1.0
author: BadDevelopers
main: com.BadDevelopers.SkypixelHyblock.Main
description: Our own spin on Hypixel Skyblock!
api-version: 1.16
depend: [WorldEdit]
load: startup

commands:
  skygive:
    description: Gives you a skyblock-registered item!
    usage: /skygive <playername> <skyblock ID> <quantity>   
  skycoin:
    description: Gives you skyblock coins!
    usage: /skycoin <playername> <action> <quantity>
  skyskill:
    description: If you're seeing this, I've fucked up...
    usage: If you're seeing this, I've fucked up...
  skyenchant:
    description: Enchants a held item!
    usage: /skyenchant <playername> <enchantment> <level>