name: KingdomsOfElgardia
version: 1.0
author: BadDevelopers
main: com.BadDevelopers.SkypixelHyblock.Main
description: Our own RPG-Style Minecraft gamemode.
api-version: 1.16
depend: [WorldEdit]
load: startup

commands:
  give:
    description: Gives you a KoE-registered item!
    usage: /give <playername> <KoE ID> <quantity>   
  coin:
    description: Gives you KoE coins!
    usage: /coin <playername> <action> <quantity>
  skill:
    description: Gives you KoE skills!
    usage: /skill <playername> <action> <skill> <quantity>
  enchant:
    description: Enchants a held item! (currently disabled)
    usage: /enchant <playername> <enchantment> <level>
  summon:
    description: Summons a custom entity!
    usage: /summon <entity type>
  ride:
    description: allows an entity to ride another entity!
    usage: /ride <entity uuid> <entity uuid>